from __future__ import annotations

from src.models.schemas import Industry, LeadCandidate, ScoredLead


class LeadScorer:
    def score(self, lead: LeadCandidate) -> ScoredLead:
        online = sum(bool(v) for v in [lead.website, lead.email, lead.social_url])
        phone = 15 if lead.phone_number else 0
        org = self._size_score(lead.estimated_organization_size)
        workflow = 25 if lead.industry == Industry.school else 22
        digital = min(20, online * 7)
        complexity = min(100, org + workflow + digital + phone)
        saas = min(100, complexity + (10 if lead.industry == Industry.school else 14))
        lead_score = min(100, int((complexity * 0.45) + (saas * 0.4) + (phone + digital) * 0.15))

        if lead.industry == Industry.school:
            challenges = "Admissions tracking, fee follow-ups, parent communication, staff coordination"
            entry = "Operations CRM for admissions, parent communication, and follow-up visibility"
            angle = "Lead with reducing missed parent inquiries and centralizing enrollment operations."
        else:
            challenges = "Lead intake, site survey scheduling, quotation follow-ups, installer coordination"
            entry = "Sales pipeline and operations tracker for solar installation workflows"
            angle = "Lead with faster quote follow-up and cleaner handoff from inquiry to installation."

        return ScoredLead(
            **lead.model_dump(),
            lead_score=lead_score,
            operational_complexity_score=complexity,
            saas_potential_score=saas,
            likely_operational_challenges=challenges,
            suggested_nexora_entry_point=entry,
            suggested_conversation_angle=angle,
            notes="Fresh lead generated by NEXORA SALESLEAD autonomous engine.",
        )

    @staticmethod
    def _size_score(size: str) -> int:
        text = size.lower()
        if any(token in text for token in ["large", "100", "200", "500"]):
            return 35
        if any(token in text for token in ["medium", "50", "75"]):
            return 28
        if any(token in text for token in ["small", "10", "20"]):
            return 18
        return 22
